Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -39,6 +39,16 @@ jobs:
           name: maven-artifacts
           path: '**/*.war' 
 
+      - name: Download and Extract Artifact
+        run: |
+          mkdir -p temp_artifacts
+          wget -q -O temp_artifacts/maven-artifacts.tar.gz ${{ steps.upload.outputs.artifacts_location }}/maven-artifacts.tar.gz
+          if [ ! -f temp_artifacts/maven-artifacts.tar.gz ]; then
+            echo "Failed to download artifact"
+            exit 1
+          fi
+          tar -xzvf temp_artifacts/maven-artifacts.tar.gz -C temp_artifacts/
+          mv temp_artifacts/*.war temp_artifacts/deployed.war
       - name: Deploy to Tomcat on AWS EC2
         uses: appleboy/ssh-action@master
         with:
@@ -46,15 +56,26 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
           script: |
-            #sudo systemctl restart tomcat
-            sudo apt-get update
-            sudo apt-get install -y unzip
-            mkdir -p temp_artifacts
-            wget -q -O temp_artifacts/maven-artifacts.tar.gz ${{ steps.upload.outputs.artifacts_location }}/maven-artifacts.tar.gz
-            if [ ! -f temp_artifacts/maven-artifacts.tar.gz ]; then
-              echo "Failed to download artifact"
-              exit 1
-            fi
-            tar -xzvf temp_artifacts/maven-artifacts.tar.gz -C temp_artifacts/ || { echo "Failed to extract artifact"; exit 1; }
-            cp maven-artifacts/*.war tomcat:/bitnami/tomcat/webapps/*.war
+            sudo systemctl restart tomcat
+            scp temp_artifacts/deployed.war ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:tomcat:/bitnami/tomcat/webapps/
+
+
+      # - name: Deploy to Tomcat on AWS EC2
+      #   uses: appleboy/ssh-action@master
+      #   with:
+      #     host: ${{ secrets.EC2_HOST }}
+      #     username: ${{ secrets.EC2_USERNAME }}
+      #     key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
+      #     script: |
+      #       #sudo systemctl restart tomcat
+      #       sudo apt-get update
+      #       sudo apt-get install -y unzip
+      #       mkdir -p temp_artifacts
+      #       wget -q -O temp_artifacts/maven-artifacts.tar.gz ${{ steps.upload.outputs.artifacts_location }}/maven-artifacts.tar.gz
+      #       if [ ! -f temp_artifacts/maven-artifacts.tar.gz ]; then
+      #         echo "Failed to download artifact"
+      #         exit 1
+      #       fi
+      #       tar -xzvf temp_artifacts/maven-artifacts.tar.gz -C temp_artifacts/ || { echo "Failed to extract artifact"; exit 1; }
+      #       cp maven-artifacts/*.war tomcat:/bitnami/tomcat/webapps/*.war
 
